In [2]:
from jqdatasdk import *
import os
JQ_PHONE = os.getenv('JQ_PHONE')
JQ_PWD = os.getenv('JQ_PWD')

In [3]:
auth(JQ_PHONE, JQ_PWD)

auth success

In [13]:
get_price(['600519.XSHG', '000001.XSHE'], start_date='2023-02-06', end_date='2023-02-14')

,time,code,open,close,high,low,volume,money
0,2023-02-06,000001.XSHE,14.10,14.00,14.13,13.86,131761010.0,1.838429e+09
1,2023-02-07,000001.XSHE,14.06,14.21,14.32,14.03,86946046.0,1.235298e+09
2,2023-02-08,000001.XSHE,14.24,14.04,14.32,14.03,65789257.0,9.287089e+08
3,2023-02-09,000001.XSHE,14.01,14.13,14.30,13.96,83035002.0,1.174362e+09
4,2023-02-10,000001.XSHE,14.10,13.98,14.12,13.86,84728366.0,1.184283e+09
5,2023-02-13,000001.XSHE,13.94,13.82,13.94,13.60,180005416.0,2.473405e+09
6,2023-02-14,000001.XSHE,13.85,13.96,13.98,13.80,90993709.0,1.263892e+09
7,2023-02-06,600519.XSHG,1780.00,1795.00,1795.00,1760.00,4266095.0,7.595739e+09
8,2023-02-07,600519.XSHG,1808.08,1797.00,1808.80,1787.73,2432171.0,4.373672e+09
9,2023-02-08,600519.XSHG,1800.01,1784.00,1805.97,1775.00,1667577.0,2.980575e+09
10,2023-02-09,600519.XSHG,1778.00,1818.00,1829.75,1775.01,2975366.0,5.401399e+09
11,2023-02-10,600519.XSHG,1810.10,1810.00,1818.49,1801.05,1798451.0,3.253859e+09
12,2023-02-13,600519.XSHG,1810.00,1856.35,1874.50,1810.00,3814670.0,7.058382e+09
13,2023-02-14,600519.XSHG,1856.46,1843.79,1857.40,1835.00,1956576.0,3.601770e+09

In [8]:
# 获取多只期货
panel =  get_price(['IC1505.CCFX', 'IC1506.CCFX'], start_date='2015-05-06', end_date='2015-05-08') # 获取中IC1505和IC1506的天数据, 返回一个[pandas.Panel]
df_open = panel['open']  # 获取开盘价的[pandas.DataFrame],  行索引是[datetime.datetime]对象, 列索引是期货代号
df_volume = panel['volume']  # 获取交易量的[pandas.DataFrame]

In [15]:
# 获取所有A股
get_all_securities(['stock'])

            display_name  name start_date   end_date   type
000001.XSHE         平安银行  PAYH 1991-04-03 2200-01-01  stock
000002.XSHE          万科A   WKA 1991-01-29 2200-01-01  stock
000004.XSHE         ST国华  STGH 1990-12-01 2200-01-01  stock
000005.XSHE         ST星源  STXY 1990-12-10 2200-01-01  stock
000006.XSHE         深振业A  SZYA 1992-04-27 2200-01-01  stock
...                  ...   ...        ...        ...    ...
688799.XSHG         华纳药厂  HNYC 2021-07-13 2200-01-01  stock
688800.XSHG          瑞可达   RKD 2021-07-22 2200-01-01  stock
688819.XSHG         天能股份  TNGF 2021-01-18 2200-01-01  stock
688981.XSHG         中芯国际  ZXGJ 2020-07-16 2200-01-01  stock
689009.XSHG         九号公司  JHGS 2020-10-29 2200-01-01  stock

[5085 rows x 5 columns]